### ISSUE TITLE
Use typewrite with Angular translate

### ISSUE THREAD

**Issue by nilsi** [antoniocapelo/angular-typewrite#2]
Hi, 

Is there any way I can use this directive with Angular translate?
I have translations like ```{{ 'HEADLINE' | translate }}``` that I can't pass that to the text attribute. Not sure if I can edit the directive or make angular parse the expression before passing it to typewrite. Will look into it but was wondering if you have any idea of how to do this?

**Comment by antoniocapelo** [comment]
Hi,

Making adapters for ng-translate shouldn't be hard, as long as the translateProvider is previously configured. But instead of changing this directive, have you tried to use the $translate service on the controller  and assign the translation to a scope variable?

    $scope.headline = $translate.instant('HEADLINE');

and then on the directive you could pass the $scope.headline var as the text attribute

**Comment by nilsi** [comment]
Thank you!

Your right, that would work but seems like the directive is running before my translations are loaded.

So ```$scope.start = $translate.instant('HEADLINE');``` is typing out HEADLINE on the page

But if I do:
```
$translate('START').then(function (translation) {
    $scope.start = translation;
    console.log('in translate callback : ' + $scope.start);
});
 ```
Nothing gets typed but when the callback comes it prints the value of my my headline in the console.
Im not sure how to make the directive wait for the translation to be loaded. 
This is not really related to your directive, so feel free to close this issue if you want. And also if you have any idea how I could solve this that would be greatly appreciated.

Thanks again for a great plugin!

**Comment by antoniocapelo** [comment]
This is a "particularity" of angular. The directive is being initialized before the translations promise has been fulfilled. 
One trick to make sure the directive is only initialised when you want is to use a ng-if on the directive that depends on a variable that only gets resolved when the promise is resolved.

    $scope.translationReady = false;
    $translate('HEADLINE').then(function (translation) {
        $scope.headline = translation;
        $scope.translationReady = false;
    });

and on the view:

    <h1 ng-if="translationReady" typewrite text="headline"></h1>

Or better yet, use the variable that will hold the translation as the condition for the ng-if:

    $translate('HEADLINE').then(function (translation) {
        $scope.headline = translation;
    });

and on the view:
    
    <h1 ng-if="headline" typewrite text="headline"></h1>

Hope this helps!
(if so, tell me so that I can close the issue)
Cheers

**Comment by nilsi** [comment]
That worked wonderfully! Thank you very much, it's so easy when I see it but couldn't find a solution..
